version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_WS_URL=${VITE_WS_URL}
        - VITE_CREDENTIALS_KEY=${VITE_CREDENTIALS_KEY}
        - VITE_PROXY_BINANCE_AUTH=${VITE_PROXY_BINANCE_AUTH}
        - VITE_PROXY_BLOFIN_AUTH=${VITE_PROXY_BLOFIN_AUTH}
    ports:
      - "3001:3001"
    restart: always
    networks:
      - 247-databases_app-network
    container_name: 247-terminal-pwa-v2

networks:
  247-databases_app-network:
    external: true
